### PR TITLE
Enable TravisCI

### PR DESCRIPTION
**Pull request by yuanfeiz**

### CODE REVIEW

**Comment by Arachnid** [comment]
Thanks! Can you rebase against the current master?

**Comment by yuanfeiz** [comment]
Sure, still fixing the tests, would do before merging :)

**Comment by yuanfeiz** [comment]
@Arachnid all set, ready to be reviewed.

**Comment by Arachnid** [comment]
Thanks very much. This was on my todo list, but I'm glad you got to it first. :)

**Comment by Arachnid** [comment]
Looks like it's expecting a rakefile? https://travis-ci.org/ethereum/ens/builds/215588850

**Pull request merged**
